__package_name__ = "juno_snp"
__authors__ = "Alejandra Hernández Segura, Roxanne Wolthuis and Boas van der Putten"
__email__ = "ids-bioinformatics@rivm.nl"
__version__ = "1.1.0"
__description__ = "Juno-SNP pipeline for bacterial SNP analysis of a single batch"